name: CI/CD
on: [push]
jobs:
  cypress-tests:
    name: Build & run Cypress tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/basic-routing.spec.js
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:3000"
        env:
          REACT_APP_DEV_MAP_VIEW: "False"
          REACT_APP_USE_DEFAULT_OD: "False"
          REACT_APP_DEBUG_GRAPH: "False"
          REACT_APP_GP_SERVER: ${{ secrets.REACT_APP_GP_SERVER }}
          REACT_APP_MB_ACCESS: ${{ secrets.REACT_APP_MB_ACCESS }}
          REACT_APP_FB_API_KEY: ${{ secrets.REACT_APP_FB_API_KEY }}
          REACT_APP_FB_MSG_SENDER_ID: ${{ secrets.REACT_APP_FB_MSG_SENDER_ID }}
          REACT_APP_FB_APP_ID: ${{ secrets.REACT_APP_FB_APP_ID }}
          REACT_APP_FB_MEASUREMENT_ID: ${{ secrets.REACT_APP_FB_MEASUREMENT_ID }}
